---
  
- name: Get consul-template package checksum file
  get_url:
    url: "{{ consul_template_checksum_file_url }}"
    dest: "{{ consul_template_work_dir }}"
  when: not installed|default(false)

- name: Get checksum of consul-template package
  shell: >
    grep {{ consul_template_pkg }} {{ consul_template_work_dir }}/{{ consul_template_checksum_file }}
  register: chksum
  when: not installed|default(false)

- name: Download consul-template package
  get_url:
    url:      "{{ consul_template_pkg_url }}"
    dest:     "{{ consul_template_work_dir }}/{{ consul_template_pkg }}"
    checksum: "sha256:{{ chksum.stdout.split(' ')|first }}"
  when: not installed|default(false)

- name: Install consul-template
  unarchive: 
    src:  "{{ consul_template_work_dir }}/{{ consul_template_pkg }}"
    dest: "{{ consul_template_bin_dir }}"
    copy: no
  when: not installed|default(false)
  notify: Restart consul-template
