---

- name: Create consul-template group
  group: name="{{ consul_template_group }}"

- name: Create consul-template user
  user: 
    name:  "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    shell: "/bin/bash"
    home:  "{{ consul_template_work_dir }}"
    createhome: no
    state: present

- name: Install unzip
  apt: name=unzip state=present

- name: Create consul-template directory structure
  file:
    dest:  "{{ item }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode:  0755
    state: directory
  with_items:
    - "{{ consul_template_work_dir }}"
    - "{{ consul_template_conf_dir }}"
    - "{{ consul_template_log_dir }}"

- name: Create consul-template bin directory
  file: dest={{ consul_template_bin_dir }} mode=0755 state=directory

- name: Get consul-template package checksum file
  get_url:
    url: "{{ consul_template_checksum_file_url }}"
    dest: "{{ consul_template_work_dir }}"

- name: Get checksum of consul-template package
  shell: >
    grep {{ consul_template_pkg }} {{ consul_template_work_dir }}/{{ consul_template_checksum_file }}
  register: chksum

- name: Download consul-template package
  get_url:
    url:      "{{ consul_template_pkg_url }}"
    dest:     "{{ consul_template_work_dir }}/{{ consul_template_pkg }}"
    checksum: "sha256:{{ chksum.stdout.split(' ')|first }}"

- name: Install consul-template
  unarchive: 
    src:  "{{ consul_template_work_dir }}/{{ consul_template_pkg }}"
    dest: "{{ consul_template_bin_dir }}"
    copy: no

- name: Create consul-template init script
  template:
    src:   consul-template.init.j2
    dest:  /etc/init.d/consul-template
    owner: root
    group: root
    mode:  0755
  notify: Restart consul-template

- name: Create consult-template defaults config file
  template:
    src:   defaults.conf.j2
    dest:  "{{ consul_template_conf_dir }}/defaults.conf"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode:  0644
  notify: Restart consul-template
