---

- name: Ensure that consul-template template file to render is present
  stat: path="{{ consul_template_template.source }}" 
  register: t

- set_fact: tmplcfg={{ consul_template_template.source.split('/')[-1]|replace('.ctmpl', '') }}
- debug: var=tmplcfg

- name: Fail if consul-template template file does not exist
  fail: msg="CRITICAL - template file to render is missing"
  when: not t.stat.exists

- name: Render consul-template template file
  template:
    src:   template.conf.j2
    dest:  "{{ consul_template_conf_dir }}/template-{{ tmplcfg }}"
    owner: root
    group: root
    mode:  0644
  notify: Restart consul-template
