---

- name: Ensure that consul-template template file to render is present
  stat: path="{{ consul_template_template.source }}" 
  register: t

- set_fact: tmplcfg={{ consul_template_template.source.split('/')[-1] | replace('.ctmpl', '') }}
- debug: var=tmplcfg

- name: Fail if consul-template template file does not exist OR contents was not provided
  fail: msg="CRITICAL - template file to render is missing AND contents was not provided"
  when: (not t.stat.exists) and (consul_template_template.contents is not defined)

- name: Render consul-template template file
  template:
    src:   template.conf.j2
    dest:  "{{ consul_template_conf_dir }}/template-{{ tmplcfg }}"
    owner: root
    group: root
    mode:  0644
  notify: Reload consul-template
