---

- name: Restart consul-template
  service: name=consul-template state=restarted
  when: not consul_template_do_not_start_immediately

- name: Reload consul-template
  service: name=consul-template state=reloaded
  when: not consul_template_do_not_start_immediately
